// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtJfAwyE0jI8IDCF8jN0P1qGSN95p50ao',
    appId: '1:245999537606:web:bafad32992f4f06895f6c7',
    messagingSenderId: '245999537606',
    projectId: 'tiktok-clone-230217',
    authDomain: 'tiktok-clone-230217.firebaseapp.com',
    storageBucket: 'tiktok-clone-230217.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZr2KVqIwQ1YFeRGjz_RmkdHGirrtBz3s',
    appId: '1:245999537606:android:aae1767ef36409fb95f6c7',
    messagingSenderId: '245999537606',
    projectId: 'tiktok-clone-230217',
    storageBucket: 'tiktok-clone-230217.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUttVNoYf60ZmaF1yEf9XezUY_bc1JokQ',
    appId: '1:245999537606:ios:4025b94769fbe7f995f6c7',
    messagingSenderId: '245999537606',
    projectId: 'tiktok-clone-230217',
    storageBucket: 'tiktok-clone-230217.firebasestorage.app',
    iosBundleId: 'com.zeronedev.tiktok230217',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtJfAwyE0jI8IDCF8jN0P1qGSN95p50ao',
    appId: '1:245999537606:web:8a91b36f0a2c62e695f6c7',
    messagingSenderId: '245999537606',
    projectId: 'tiktok-clone-230217',
    authDomain: 'tiktok-clone-230217.firebaseapp.com',
    storageBucket: 'tiktok-clone-230217.firebasestorage.app',
  );
}